#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=lib/common.sh
source "$(dirname "$0")/lib/common.sh"

log "20-clone-and-env"

need_cmd git
need_env CUSTOMER_DOMAIN
need_env PORTAL_URL
need_env LICENSE_API_SIGNING_SECRET

export CUSTOMER_DOMAIN="$(normalize_domain "$CUSTOMER_DOMAIN")"
APP_URL="https://${CUSTOMER_DOMAIN}"

export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_hex_32)}"
export AUTH_SECRET="${AUTH_SECRET:-$(gen_b64_32)}"
export DATA_ENCRYPTION_KEY="${DATA_ENCRYPTION_KEY:-$(gen_b64_32)}"
export CRON_SECRET="${CRON_SECRET:-$(gen_hex_32)}"

if [[ -d "$INSTALL_DIR/.git" ]]; then
  log "Updating existing clone at $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch origin "$REPO_BRANCH"
  git -C "$INSTALL_DIR" checkout "$REPO_BRANCH"
  git -C "$INSTALL_DIR" pull --ff-only origin "$REPO_BRANCH" || git -C "$INSTALL_DIR" reset --hard "origin/$REPO_BRANCH"
else
  log "Cloning $REPO_URL → $INSTALL_DIR"
  sudo mkdir -p "$(dirname "$INSTALL_DIR")"
  if [[ -d "$INSTALL_DIR" ]]; then
    sudo rm -rf "$INSTALL_DIR"
  fi
  sudo git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
  sudo chown -R "${SUDO_USER:-root}:$(id -gn "${SUDO_USER:-root}")" "$INSTALL_DIR" 2>/dev/null || true
fi

ENV_FILE="$INSTALL_DIR/.env.production"
log "Writing $ENV_FILE"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/provision/20-clone-and-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATABASE_URL=postgresql://nexus:${POSTGRES_PASSWORD}@postgres:5432/nexus?schema=public
DIRECT_URL=postgresql://nexus:${POSTGRES_PASSWORD}@postgres:5432/nexus?schema=public

AUTH_TRUST_HOST=true
AUTH_URL=${APP_URL}
NEXTAUTH_URL=${APP_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}

AUTH_SECRET=${AUTH_SECRET}
DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
CRON_SECRET=${CRON_SECRET}

ENABLE_BACKGROUND_JOBS=true
IMEI_ORDER_SCHEDULER_ENABLED=true
SERVER_ORDER_SCHEDULER_ENABLED=true
WEBHOOK_SCHEDULER_ENABLED=true
BACKUP_SCHEDULER_ENABLED=true
IMEI_ORDER_POLL_INTERVAL_MS=90000
WEBHOOK_POLL_INTERVAL_MS=60000

BACKUP_DIR=/app/storage/backups

NEXUS_LICENSE_SERVER_URL=${PORTAL_URL%/}
LICENSE_API_SIGNING_SECRET=${LICENSE_API_SIGNING_SECRET}
EOF

if [[ -n "${LICENSE_KEY:-}" ]]; then
  printf '\n# Activate in admin UI after deploy: License → System\nNEXUS_LICENSE_KEY=%s\n' "$LICENSE_KEY" >>"$ENV_FILE"
fi

chmod 600 "$ENV_FILE"
log "Environment file written (secrets generated on VPS — D3)"
