#!/usr/bin/env bash
set -euo pipefail
# shellcheck source=lib/common.sh
source "$(dirname "$0")/lib/common.sh"

log "20-setup-env (image-based — no app source on VPS)"

need_env CUSTOMER_DOMAIN
need_env PORTAL_URL
need_env LICENSE_API_SIGNING_SECRET
need_env NEXUS_IMAGE

export CUSTOMER_DOMAIN="$(normalize_domain "$CUSTOMER_DOMAIN")"
APP_URL="https://${CUSTOMER_DOMAIN}"

ENV_FILE="$INSTALL_DIR/.env.production"
if [[ -f "$ENV_FILE" ]]; then
  log "Reusing secrets from existing $ENV_FILE (safe for retries with existing pgdata volume)"
  export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(grep '^DATABASE_URL=' "$ENV_FILE" | sed -n 's/.*nexus:\([^@]*\)@.*/\1/p')}"
  export AUTH_SECRET="${AUTH_SECRET:-$(env_value_from_file "$ENV_FILE" AUTH_SECRET || true)}"
  export DATA_ENCRYPTION_KEY="${DATA_ENCRYPTION_KEY:-$(env_value_from_file "$ENV_FILE" DATA_ENCRYPTION_KEY || true)}"
  export CRON_SECRET="${CRON_SECRET:-$(env_value_from_file "$ENV_FILE" CRON_SECRET || true)}"
fi

export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_hex_32)}"
export AUTH_SECRET="${AUTH_SECRET:-$(gen_b64_32)}"
export DATA_ENCRYPTION_KEY="${DATA_ENCRYPTION_KEY:-$(gen_b64_32)}"
export CRON_SECRET="${CRON_SECRET:-$(gen_hex_32)}"

TEMPLATES="$PROVISION_DIR/templates"
[[ -f "$TEMPLATES/docker-compose.stack.yml" ]] || die "Missing $TEMPLATES/docker-compose.stack.yml"

log "Preparing install dir $INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR/deploy"
sudo cp "$TEMPLATES/docker-compose.stack.yml" "$INSTALL_DIR/docker-compose.stack.yml"
sudo cp "$TEMPLATES/docker-compose.caddy.yml" "$INSTALL_DIR/docker-compose.caddy.yml"
sudo chown -R "${SUDO_USER:-root}:$(id -gn "${SUDO_USER:-root}")" "$INSTALL_DIR" 2>/dev/null || true

log "Writing $ENV_FILE"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/provision/20-setup-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATABASE_URL=postgresql://nexus:${POSTGRES_PASSWORD}@postgres:5432/nexus?schema=public
DIRECT_URL=postgresql://nexus:${POSTGRES_PASSWORD}@postgres:5432/nexus?schema=public

AUTH_TRUST_HOST=true
AUTH_URL=${APP_URL}
NEXTAUTH_URL=${APP_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}

AUTH_SECRET=${AUTH_SECRET}
DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
CRON_SECRET=${CRON_SECRET}

ENABLE_BACKGROUND_JOBS=true
IMEI_ORDER_SCHEDULER_ENABLED=true
SERVER_ORDER_SCHEDULER_ENABLED=true
WEBHOOK_SCHEDULER_ENABLED=true
BACKUP_SCHEDULER_ENABLED=true
IMEI_ORDER_POLL_INTERVAL_MS=90000
WEBHOOK_POLL_INTERVAL_MS=60000

BACKUP_DIR=/app/storage/backups

NEXUS_LICENSE_SERVER_URL=${PORTAL_URL%/}
LICENSE_API_SIGNING_SECRET=${LICENSE_API_SIGNING_SECRET}
EOF

if [[ -n "${LICENSE_KEY:-}" ]]; then
  printf '\n# Activate in admin UI after deploy: License → System\nNEXUS_LICENSE_KEY=%s\n' "$LICENSE_KEY" >>"$ENV_FILE"
fi

chmod 600 "$ENV_FILE"
log "Environment + compose templates ready (NEXUS_IMAGE=$NEXUS_IMAGE)"
